preset: laravel

enabled:
 - ereg_to_preg
 - modernize_types_casting
 - no_php4_constructor
 - php_unit_construct
 - php_unit_strict
 - echo_to_print
 - align_equals
 - align_double_arrow
 - no_short_echo_tag

disabled:
 - whitespace_after_comma_in_array
 - space_after_semicolon
 - not_operator_with_successor_space
 - print_to_echo
 - psr4
 - simplified_null_return
 - unalign_equals
 - trailing_comma_in_multiline_array

finder:
 exclude:
  - "language"
  - "vendors"
  - "vendor"
